spring:
  threads:
    virtual:
      enabled: true

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

server:
  shutdown: graceful